ALTER TABLE behavior_events
ADD COLUMN IF NOT EXISTS avg_hold_time DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS avg_flight_time DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_keystrokes INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS profile_deviation_score DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS detect_anomaly BOOLEAN NOT NULL DEFAULT FALSE;