ALTER TABLE behavior_events
ADD COLUMN IF NOT EXISTS behavior_score DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS identity_score DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS baseline_status VARCHAR NOT NULL DEFAULT 'INSUFFICIENT_DATA',
ADD COLUMN IF NOT EXISTS reasons JSON NOT NULL DEFAULT '[]';