ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(10);

UPDATE users
SET role = 'USER'
WHERE role IS NULL;

ALTER TABLE users
ALTER COLUMN role SET DEFAULT 'USER';

ALTER TABLE users
ALTER COLUMN role SET NOT NULL;

ALTER TABLE users
DROP CONSTRAINT IF EXISTS users_role_check;

ALTER TABLE users
ADD CONSTRAINT users_role_check
CHECK (role IN ('USER', 'ADMIN'));
